# Generated by Django 4.0.5 on 2022-06-04 18:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='', max_length=30)),
                ('phone_number', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateField(null=True)),
                ('yoe', models.IntegerField()),
                ('highest_qualification', models.CharField(max_length=64)),
                ('linkedin', models.URLField()),
                ('skills', models.CharField(max_length=400)),
                ('dp', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Mafioso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=30, null=True)),
                ('password2', models.CharField(max_length=30, null=True)),
                ('job_description', models.CharField(max_length=600)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ReferalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bumble.applicant')),
                ('mafioso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bumble.mafioso')),
            ],
        ),
    ]
